[package]
name = "probes"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ownership"
path = "src/ownership/main.rs"
required-features = ["probes"]

[dependencies]
std_ownership = { path = "../../core/" }