[package]
name = "std_ownership"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
libc = "0.2"
strum = "0.24"
crossbeam = "0.8.2"
parking_lot = "0.12.1"
std_ownership_api = { path = "../api/" }