name: Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04-4core-16gb

    steps:
    - uses: actions/checkout@v3
    - name: Benches
      run: cargo bench -p benches -j 16
